/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
// import GameUI from "./script/GameUI"
// import GameControl from "./E:/LY2.6.0/resources/app/out/vs/layaEditor/src/script/GameControl"
// import Bullet from "./E:/LY2.6.0/resources/app/out/vs/layaEditor/src/script/Bullet"
// import DropBox from "./E:/LY2.6.0/resources/app/out/vs/layaEditor/src/script/DropBox"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="test/TestScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        // var reg: Function = Laya.ClassUtils.regClass;
        // reg("script/GameUI.ts",GameUI);
        // reg("E:/LY2.6.0/resources/app/out/vs/layaEditor/src/script/GameControl.ts",GameControl);
        // reg("E:/LY2.6.0/resources/app/out/vs/layaEditor/src/script/Bullet.ts",Bullet);
        // reg("E:/LY2.6.0/resources/app/out/vs/layaEditor/src/script/DropBox.ts",DropBox);
    }
}
GameConfig.init();